import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { ArrowRight, BarChart3, BriefcaseBusiness, Code2, GraduationCap, HeartPulse, MapPin, Plus, Search, Sparkles, WalletCards } from "lucide-react";
import { useMemo, useState } from "react";
import { AppShell } from "@/components/app-shell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { newEvaluationSearchForTemplate } from "@/lib/new-evaluation-search";

export const Route=createFileRoute("/_authenticated/templates")({component:Templates});
const templates=[
  {title:"AI Study Companion",description:"AI copilot that helps students find and summarize notes from previous years.",industry:"EdTech",stage:"Idea",icon:GraduationCap},
  {title:"FinTrack",description:"Personal finance and cash-flow app designed for independent freelancers.",industry:"Fintech",stage:"MVP",icon:WalletCards},
  {title:"LocalEats",description:"A hyperlocal food delivery marketplace connecting diners with neighborhood kitchens.",industry:"Marketplace",stage:"Idea",icon:MapPin},
  {title:"CodeReview AI",description:"AI-powered code review assistant for faster, safer engineering releases.",industry:"Developer Tools",stage:"MVP",icon:Code2},
  {title:"CarePath",description:"A patient navigation platform that simplifies care plans and follow-up.",industry:"Healthcare",stage:"Early Revenue",icon:HeartPulse},
  {title:"B2B Signal",description:"A sales intelligence product that identifies high-intent company accounts.",industry:"SaaS",stage:"Idea",icon:BriefcaseBusiness},
];
function Templates(){const nav=useNavigate();const[q,setQ]=useState("");const[filter,setFilter]=useState("All");const visible=useMemo(()=>templates.filter(item=>(filter==="All"||item.industry===filter)&&`${item.title} ${item.description}`.toLowerCase().includes(q.toLowerCase())),[q,filter]);const useTemplate=(item:typeof templates[number])=>nav({to:"/new-evaluation",search:newEvaluationSearchForTemplate(item.title)});return <AppShell><div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-primary">Startup presets</p><h1 className="mt-2 text-3xl">Evaluation Templates</h1><p className="mt-2 text-xs text-muted-foreground">Start with a proven structure, then tailor the idea before running your agents.</p></div><Button variant="hero" asChild><a href="#templates"><Plus/>Browse Templates</a></Button></div><div className="mt-8 flex flex-wrap gap-2"><div className="relative min-w-64 flex-1"><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground"/><Input value={q} onChange={event=>setQ(event.target.value)} placeholder="Search templates…" className="pl-9"/></div>{["All","EdTech","Fintech","Marketplace","Developer Tools"].map(item=><Button key={item} variant={filter===item?"default":"outline"} size="sm" onClick={()=>setFilter(item)}>{item}</Button>)}</div><div id="templates" className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{visible.map(item=><article key={item.title} className="group border border-border bg-card p-6 transition-colors hover:border-primary/40"><div className="flex items-start justify-between"><span className="grid h-10 w-10 place-items-center rounded-full bg-accent text-primary"><item.icon className="h-5 w-5"/></span><span className="text-[9px] uppercase tracking-wider text-muted-foreground">{item.stage}</span></div><h2 className="mt-6 font-sans text-sm font-semibold">{item.title}</h2><p className="mt-2 min-h-12 text-xs leading-5 text-muted-foreground">{item.description}</p><div className="mt-5 flex items-center justify-between border-t border-border pt-4"><span className="flex items-center gap-1 text-[10px] text-primary"><BarChart3 className="h-3 w-3"/>{item.industry}</span><Button variant="ghost" size="sm" onClick={()=>useTemplate(item)}>Study template<ArrowRight/></Button></div></article>)}</div>{visible.length===0&&<div className="mt-8 border border-border bg-card p-14 text-center"><Sparkles className="mx-auto h-6 w-6 text-primary"/><p className="mt-3 text-sm font-medium">No matching templates</p></div>}</div></AppShell>}